fix: use global() to get performance API on wasm32-unknown-unknown
metrics-rs/quanta pull request #107
Opened 2024-11-23 14:02 UTC by Officeyutong

Currently quanta uses `window.performance` to access Performance API in browser, which will not work in WebWorkers. In WebWorkers, there is no `window` object, but `performance` is in the global space.

This PR uses `web_sys::js_sys::global()` to access the global scope, and look up for `performance` in that, which will both work on webpage and WebWorkers.

See https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers for more details

2024-11-25 23:41 UTC, tobz reviewed
Thanks for opening this PR!

Taking a look at the code, it seems like this is going to be somewhat inefficient, reflecting through the global scope on every single call.

Is my intuition wrong here? Could we not instead simply query for the `Performance` class when constructing `Monotonic` so that there's always a live reference to it to directly use?

2024-11-26 13:26 UTC, Officeyutong commented
> Thanks for opening this PR!
> 
> Taking a look at the code, it seems like this is going to be somewhat inefficient, reflecting through the global scope on every single call.
> 
> Is my intuition wrong here? Could we not instead simply query for the `Performance` class when constructing `Monotonic` so that there's always a live reference to it to directly use?

You are right, Reflection is relatively slow since its equal to `object[attribute]` in JS. I'll try to store a reference to `Performance` class to avoid frequent call to Reflection

2024-11-27 08:51 UTC, Officeyutong commented
> Thanks for opening this PR!
> 
> Taking a look at the code, it seems like this is going to be somewhat inefficient, reflecting through the global scope on every single call.
> 
> Is my intuition wrong here? Could we not instead simply query for the `Performance` class when constructing `Monotonic` so that there's always a live reference to it to directly use?

Updated now. I also splitted `wasm.rs` to `wasm_browser.rs` and `wasm_wasi.rs`, since implementation of these two platforms are completely different

2024-12-05 13:24 UTC, Officeyutong commented
Hi @tobz , how's this issue going on?

2024-12-05 14:12 UTC, tobz requested changes
Apologies: life and work have been pretty busy lately. :)

I left a common about how we caching the `Performance` object, and in particular about how we're overriding the fact that it's `!Send`/`!Sync`.

2024-12-08 18:10 UTC, tobz commented on Cargo.toml
> +rust-version = "1.70"
I just realized we were changing the MSRV here, but it's not clear why.

2024-12-09 08:50 UTC, Officeyutong commented on Cargo.toml
> +rust-version = "1.70"
`OnceCell` was stable since `1.70`, see https://doc.rust-lang.org/stable/src/core/cell/once.rs.html#31

2024-12-09 13:28 UTC, tobz commented on Cargo.toml
> +rust-version = "1.70"
Ah right, makes sense.

2024-12-09 13:28 UTC, tobz approved these changes
Overall, these changes seem reasonable to me. 👍🏻

2024-12-12 09:01 UTC, Officeyutong commented
> Overall, these changes seem reasonable to me. 👍🏻

Hi, when can we get this PR merged

2024-12-12 20:16 UTC, tobz commented
👋🏻 

Going to merge these now, but I'll have to fix the MSRV and CI afterwards and make sure things are still green before I can cut a release.

2024-12-12 20:16 UTC, merged

2024-12-13 03:36 UTC, tobz commented
Released as `quanta@v0.12.4`.

Thanks again for your contribution!