Clock.delta_as_nanos, a delta that skips conversion to Duration
metrics-rs/quanta pull request #86
Opened 2023-05-25 15:08 UTC by antifuchs

This change addresses #84 and should results in a benchmark that's 2ns faster (on a m1 max macOS machine) than the corresponding Duration-converting benchmark.

## Relevant Benchmarks

These look great - 2ns on the mac and 7ns on my linux testbed: I think high-frequency usage of the raw quanta functions will benefit a lot from using `delta_as_nanos`.

### macOS (m1 max)

```
quanta/quanta_raw_delta time:   [16.591 ns 16.620 ns 16.648 ns]
Found 26 outliers among 100 measurements (26.00%)
  6 (6.00%) low severe
  2 (2.00%) low mild
  5 (5.00%) high mild
  13 (13.00%) high severe
quanta/quanta_raw_delta_as_nanos
                        time:   [14.150 ns 14.163 ns 14.176 ns]
Found 12 outliers among 100 measurements (12.00%)
  5 (5.00%) high mild
  7 (7.00%) high severe
```

### Linux (dual Xeon Silver 4114)

```
quanta/quanta_raw_delta time:   [24.551 ns 24.686 ns 24.841 ns]
Found 11 outliers among 100 measurements (11.00%)
  8 (8.00%) high mild
  3 (3.00%) high severe
quanta/quanta_raw_delta_as_nanos
                        time:   [17.353 ns 17.517 ns 17.704 ns]
Found 12 outliers among 100 measurements (12.00%)
  4 (4.00%) high mild
  8 (8.00%) high severe
```

2023-05-26 16:00 UTC, tobz requested changes
Overall, looks good to me. Just some tweaks to tighten up the wording in the doc comments.

2023-05-26 19:41 UTC, antifuchs commented
Updated, thank you!

2023-05-27 14:12 UTC, tobz approved these changes

2023-05-28 14:29 UTC, merged

2023-05-28 14:42 UTC, tobz commented
Released as `quanta@v0.11.1`.

Thanks again for your contribution. ❤️

2023-05-28 22:42 UTC, antifuchs commented
Fantastic, thank you! This brings performance back to the baseline I was expecting to see! (: